apiVersion: v1
kind: Service
metadata:
  name: novohearth-homes-site
  labels:
    app: novohearth-homes-site
spec:
  type: LoadBalancer # AKS will allocate a public IP
  selector:
    app: novohearth-homes-site
  ports:
    - name: http
      port: 80 # service port
      targetPort: 80 # container port