name: CI/CD to AKS
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
       creds: ${{ secrets.AZURECREDENTIALS }}

    - name: Azure CLI version
      run: az version 
    - name: Login to ACR
      run: az acr login --name nimbusacrivqmz

    - name: Build Docker Image
      run: |
          IMAGE=nimbusacrivqmz.azurecr.io/novohearth-homes-site:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE ./Novohearth-Homes-site

    - name: Push Docker Image to ACR
      run: docker push ${{ env.IMAGE }}  

    - name: Install kubelogin
      run: az aks install-cli
    
    - name: Get AKS Credentials
      run: |
          az aks get-credentials --resource-group ${{ secrets.AZURERESOURCEGROUP }} --name ${{ secrets.AZURECLUSTERNAME }}
          kubelogin convert-kubeconfig -l azurecli
    
          

    - name: Deploy to AKS
      run: |
         kubectl set image deployment/novohearth-homes-site web=${{ env.IMAGE }}
         kubectl rollout status deployment/novohearth-homes-site


          


      
      